track_follow:

 # Public
 global_frame: /map
 plan_frequency: 50
 goal_dist_tolerance: 0.15
 slow_down_tolerance: 0.7
 prune_ahead_distance: 0.6

 # True-race False-debug
 race_sw: False

 # 0-Pure Pursuit  1-PID Position
 track_mode: 0 

 # PID Position Mode
 max_x_speed: 0.8
 max_y_speed: 0.8
 set_yaw_speed: 3.0
 p_value: 1.5
 i_value: 1.0
 d_value: 1.0

 vx_accel_limit: 0.05
 vy_accel_limit: 0.05

 # Pure Pursuit Mode
 max_yaw_speed: 0.5
 max_angle_diff: 60
